### ISSUE TITLE
Divide tags into sections

### ISSUE THREAD

**Issue by Ddedalus** [World-Youth-Days/Dictionary#9]
Tags referring to language should be separated from the rest in search box. I'm working on 'readable' and 'hidden' column in `db.tags` simultaneously.

**Comment by jdranczewski** [comment]
@Ddedalus If the tags are meant to be separated, I need a column by which I would be able to separate them - a change in the db structure is needed.

**Comment by Ddedalus** [comment]
I suppose we've already managed that issue with tag['flag'] filed. Currently `live`, `from` and `to` are in use.
